### ISSUE TITLE
Custom genome

### ISSUE THREAD

**Issue by sameet** [timoast/signac#1]
Hi,

How do I go about using `signac` with custom genome, for which the EnsDb, and BSgenome is not yet available.  Do I need to start with those two first?

Sameet

**Comment by timoast** [comment]
These are not necessary for analysis with Signac and you'll be able to do most things without it.

One thing we use the EnsDb for is supplying the gene coordinates in order to create a gene activity matrix (with the `FeatureMatrix` function), but this could be done in other ways (reading a BED or GFF file for example). You just need to supply a `GRanges` object containing the genomic intervals you want to quantify for each gene.

We also use the EnsDb annotations for plotting the gene models alongside coverage tracks, but this is optional and you can plot the coverage tracks with `CoveragePlot` without supplying an EnsDb annotation. 

The BSgenome is needed for motif analysis, which is still under development.

**Comment by sameet** [comment]
Is it possible to use the object that was created for say `CICERO` with `signac`.

**Comment by timoast** [comment]
Yes, you can add any matrix as a new assay to the object, so you could create a gene activity matrix with Cicero and then add it to the Seurat object the same way we do in the vignette, ie:

```r
object[["RNA"]] <- CreateAssayObject(counts = cicero_data)
```

**Comment by sameet** [comment]
Wonderful!! I think this will solve the problem that I currently have.  I will try this and get back to you with how it goes.  
Thank you.

**Comment by timoast** [comment]
Great, good luck!

**Comment by kyrenya** [comment]
Hi there! Have now the same question, but specifically for Motif analysis. Is it possible to do it without a BSGenome? Thanks in advance!

**Comment by timoast** [comment]
You can find enriched motifs without a BSgenome. The only requirement is a peak x motif matrix describing which peaks contain which motifs. However, in practice, it would be difficult to generate that matrix without a BSgenome object. See here for documentation for creating a BSgenome object: https://www.bioconductor.org/packages/release/bioc/vignettes/BSgenome/inst/doc/BSgenomeForge.pdf

**Comment by kyrenya** [comment]
Ok, I imagined that would be the case... Thanks a lot for your fast reply!
