### ISSUE TITLE
FindTopFeatures vs FindVariableFeatures

### ISSUE THREAD

**Issue by danielcgingerich** [timoast/signac#1015]
Why is FindTopFeatures used in signac as opposed to FindVariableFeatures for dimensionality reduction?

My end goal is to obtain reduced dimensional data with clusters that correspond to cell type and sub types.  

My understanding is that FindTopFeatures ranks peaks based on total number of cells that have it.  How does this help in separating cells by cell type?  I feel like this would select peaks associated with housekeeping genes rather than cell type markers.  Why not use FindVariableFeatures when selecting peaks for SVD?  

Also, in the vignettes often times 'q0' is used as the cutoff, which just ends up using all peaks for SVD anyways.  Is there any advantage to selecting a subset of features to use for SVD?  I looked at clusters from two different SVDs - one with all features and one with only the top 25%.  They are very similar.  

I have also experienced UMAP clusters look better when using subset of features

**Comment by timoast** [comment]
The `FindVariableFeatures()` function in Seurat is designed to find genes with higher variance than expected given their mean expression, due to the mean-variance relationship seen in scRNA-seq. It doesn't necessarily make sense to apply this method to scATAC-seq because the scATAC-seq counts follow a very different distribution, and don't have the same mean-variance relationship. The concept of "high-variance" peaks doesn't quite apply to scATAC-seq because the data has a much lower dynamic range, so really all we ask is what percentage of cells have a count for that peak. This is what the `FindTopFeatures()` function does. We found that the downstream results from LSI is quite robust to the exact peak set used. However, it can sometimes help to remove spurious peaks that are open in a very small fraction of cells.

**Comment by danielcgingerich** [comment]
@timoast this makes sense and also explains why ScaleData is not used for SVD of the atac data since the high variance concept doesnt apply.

Comparing source code between RunPCA and RunSVD they seem almost identical aside from scaling embeddings in SVD.  I still have to take linear algebra but I have always wondered what the difference is between these.  RunPCA doesnt appear to operate on the covariance matrix, as I would expect given my current understanding

**Comment by timoast** [comment]
There is a great explanation here: https://stats.stackexchange.com/questions/134282/relationship-between-svd-and-pca-how-to-use-svd-to-perform-pca

Basically, you can find the principal components via SVD, provided the data is centered.

**Comment by danielcgingerich** [comment]
@timoast Awesome! thanks for sending!
