### ISSUE TITLE
ClosestFeature

### ISSUE THREAD

**Issue by Brawni** [timoast/signac#107]
Hi Tim,

I've noticed that when using ClosestFeature inputting an ensembl object it return a list of genes pre-filtered for the protein-coding genes. Instead if you input the GRanges object it returns all the gene biotypes. These often have 0 distance from the peak where protein-coding genes are more distant. Im not sure which is the most appropriate solution?

**Comment by timoast** [comment]
Hi, this is the expected behaviour. When an EnsDb object is provided, the protein-coding genes will be extracted from the object and only these features used. If a genomic ranges object is provided, no filtering is applied. I have updated the documentation so this is more clear (https://github.com/timoast/signac/commit/c69c366438b5b140701c4811f44b2be66d001f3c)
