### ISSUE TITLE
Why are there > 2 Fragment counts when plotting per-cell fragment abundance 

### ISSUE THREAD

**Issue by Sas-cmd** [timoast/signac#1070]
I am trying to understand why there are more than 2 fragment counts as I thought in a diploid cell there should not be more than 2 fragments. 

For example, in the vignette https://satijalab.org/signac/articles/visualization.html, the are up to 5 Fragment counts. 

Obviously, my understanding is wrong, but can someone please help me understand why there are more than 2 fragments.

Thank you.

**Comment by timoast** [comment]
There are a few reasons that contribute to this:
* cut sites are counted rather than fragments (two cut sites per fragment)
* the region plotted is a window with the number of cutsites summed within the window
* ploidy of the genome may result in >2 fragments at a single site
* technical artifacts such as doublets or incorrect fragment duplicate removal

**Comment by Sas-cmd** [comment]
Hi Tim,

Thank you for your answer, is there any way in which I can remove the fragments (is it even possible?) Will this in any way affect my analysis if not removed?

Thank you.
