### ISSUE TITLE
Modify the fonts from accessibility plots (Coverage plots)

### ISSUE THREAD

**Issue by Aitor91** [timoast/signac#116]
Hello @timoast ,

I have some questions regarding the **coverageplot** function. 
- In the vignette, the gene is represented with a red arrow. However, in #17 issue, the gen is shown with its own exons (more defined). How can I produce them? 
- In the images generated by this function, the fonts are a bit small, how can I modify them? Is there a way to export the image Power-Point-friendly in order to modify it more easily?

I would appreciate any help.

Best,

Aitor

**Comment by timoast** [comment]
Hi, we dropped support for plotting genes using the ggbio package (https://github.com/timoast/signac/commit/00b71f22a7dce9549c0cc6eff0ddac95641b6dec) because it added several large dependencies and made things a bit overly complicated, and less flexible. We might think about adding gene exon/intron structures back to the plots in the future, but this is not a priority right now.

You can always plot the annotations yourself using other packages (such as [ggbio](https://bioconductor.org/packages/release/bioc/html/ggbio.html)) and combine your custom annotation plot with the coverage tracks using [patchwork](https://github.com/thomasp85/patchwork).

You can alter font sizes using standard ggplot2 functions, for example:

```r
library(ggplot2)
library(patchwork)
p <- CoveragePlot(
  object = obj,
  region = "chr14-99700000-99760000"
)
p & theme(axis.title.x = element_text(size = 20))
```

**Comment by Aitor91** [comment]
Thank you very much for your help. 
Aitor

**Comment by Aitor91** [comment]
Hi @timoast ,

So sorry for bothering you again, but I am trying to increase only the Font of the name of the gene (in the arrow) and I am not able to get it. Do you have any idea how could I do it?

Best,

Aitor

**Comment by timoast** [comment]
The gene labels are limited in their maximum size because they're plotted within the gene diagram. You could try increasing the size of the annotation track by changing the `height.tracks` parameter in `CoveragePlot` to make the gene track bigger
