### ISSUE TITLE
Motif analysis - CreateMotifMatrix error

### ISSUE THREAD

**Issue by MengyiSong** [timoast/signac#129]
Hi,
I was running the Motif analysis with my scATACseq data. I got an error when called the CreateMotifMatrix function.

Error in loadFUN(x, seqname, ranges) : 
  trying to load regions beyond the boundaries of non-circular sequence "chr15"

I think the issue is that I have a few regions that start with 0 but all the function is using 1-based as a default? (for example, the Regionstats function is also 1-based) I am wondering if you have seen such cases and how would you deal with it if I still want to keep these regions?

Thanks very much in advance!!

```r
# 
```motif.matrix <- CreateMotifMatrix(
  features = StringToGRanges(rownames(gata5wt13h), sep = c(":","-")),
  pwm = pfm,
  genome = 'danRer10',
  sep = c(":","-"),
  use.counts = FALSE
)
#it seem that I got Genomic ranges starting with 0 
#but all the motif analysis function is defualt 1 based rather than 0 based.
a[seqnames(a) == "chr15"]
GRanges object with 5974 ranges and 0 metadata columns:
         seqnames            ranges strand
            <Rle>         <IRanges>  <Rle>
     [1]    chr15             0-731      *
     [2]    chr15         1287-1506      *
     [3]    chr15         2335-2726      *
     [4]    chr15         6084-6121      *
     [5]    chr15         7685-7858      *
     ...      ...               ...    ...
  [5970]    chr15 47759714-47760899      *
  [5971]    chr15 47763914-47764082      *
  [5972]    chr15 47767490-47768047      *
  [5973]    chr15 47769372-47769778      *
  [5974]    chr15 47770567-47770968      *
  -------
  seqinfo: 25 sequences from an unspecified genome; no seqlengths

> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.2

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] ensembldb_2.8.1                     AnnotationFilter_1.8.0             
 [3] GenomicFeatures_1.36.4              AnnotationDbi_1.46.1               
 [5] Biobase_2.44.0                      AnnotationHub_2.16.1               
 [7] BiocFileCache_1.8.0                 dbplyr_1.4.2                       
 [9] ggplot2_3.3.0                       BSgenome.Drerio.UCSC.danRer10_1.4.2
[11] BSgenome_1.52.0                     rtracklayer_1.44.4                 
[13] Biostrings_2.52.0                   XVector_0.24.0                     
[15] JASPAR2016_1.12.0                   JASPAR2018_1.1.1                   
[17] JASPAR2020_0.99.8                   TFBSTools_1.22.0                   
[19] dplyr_0.8.5                         GenomicRanges_1.36.1               
[21] GenomeInfoDb_1.20.0                 IRanges_2.18.3                     
[23] S4Vectors_0.22.1                    BiocGenerics_0.30.0                
[25] Seurat_3.1.4                        Signac_0.2.4

**Comment by timoast** [comment]
Hi, in the latest version on the develop branch you can pass arguments through `StringToGRanges` to [`makeGRangesFromDataFrame`](https://www.rdocumentation.org/packages/GenomicRanges/versions/1.24.1/topics/makeGRangesFromDataFrame), so you should be able to add `starts.in.df.are.0based = TRUE` which I think will solve this issue. For example:

```r
> StringToGRanges("chr1-0-10")
GRanges object with 1 range and 0 metadata columns:
      seqnames    ranges strand
         <Rle> <IRanges>  <Rle>
  [1]     chr1      0-10      *
  -------
  seqinfo: 1 sequence from an unspecified genome; no seqlengths
> StringToGRanges("chr1-0-10", starts.in.df.are.0based=TRUE)
GRanges object with 1 range and 0 metadata columns:
      seqnames    ranges strand
         <Rle> <IRanges>  <Rle>
  [1]     chr1      1-10      *
  -------
  seqinfo: 1 sequence from an unspecified genome; no seqlengths
```

**Comment by MengyiSong** [comment]
Hi Tim,

Thanks for your quick reply! I was able to Create the matrix but when I added the motif object back to the Seurat object, I had to change the Dimname back. I think it is because the Dimname was changed to 1 based but not changed back to be stored in the motif matrix
e.g.
```
>motif.matrix@Dimnames[[1]][which(motif.matrix@Dimnames[[1]] == "chr15:1-731")] = "chr15:0-731"
```
if I don't change the name back, I will get an error as the following
```
> gata5wt13h[['peaks']] <- AddMotifObject(
           object = gata5wt13h[['peaks']],
           motif.object = motif
)
Error in AddMotifObject.Assay(object = gata5wt13h[["peaks"]], motif.object = motif) : 
  No features in common between the Assay and Motif objects
```

It seems that it is not working for the RegionStats function
```
> gata5wt13h <- RegionStats(
           object = gata5wt13h,
           genome = BSgenome.Drerio.UCSC.danRer10,
           sep = c(":", "-")
)

Error in loadFUN(x, seqname, ranges) : 
  trying to load regions beyond the boundaries of non-circular sequence "chr15"
```

I was trying to edit the RegionStats function but I was not able to get it to work. Maybe I did something wrong to the RegionStas function...
```
RegionStats <- function(
  object,
  genome,
  sep = c('-', '-'),
  verbose = TRUE,
  ...
) {
  if (inherits(x = object, what = 'character')) {
    object <- StringToGRanges(regions = object, sep = sep, starts.in.df.are.0based = TRUE)
  }
  sequence.length <- width(x = object)
  sequences <- getSeq(x = genome, names = object)
  gc <- letterFrequency(x = sequences, letters = 'CG') / sequence.length * 100
  colnames(gc) <- 'GC.percent'
  dinuc <- dinucleotideFrequency(sequences)
  sequence.stats <- cbind(dinuc, gc, sequence.length)
  rownames(sequence.stats) <- GRangesToString(grange = object, sep = sep, starts.in.df.are.0based = TRUE)
  return(sequence.stats)
}

RegionStats(
   object = test.gata5wt13h, 
   assay = "bins",
   genome = BSgenome.Drerio.UCSC.danRer10,
   sep = c(":", "-")
 )
 
 Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘width’ for signature ‘"Seurat"’
```

session info attached here:
```
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.2

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] AnnotationHub_2.16.1                BiocFileCache_1.8.0                
 [3] dbplyr_1.4.2                        ggplot2_3.3.0                      
 [5] TFBSTools_1.22.0                    dplyr_0.8.5                        
 [7] Seurat_3.1.4                        BSgenome.Drerio.UCSC.danRer10_1.4.2
 [9] BSgenome_1.52.0                     rtracklayer_1.46.0                 
[11] Biostrings_2.54.0                   XVector_0.26.0                     
[13] GenomicRanges_1.38.0                GenomeInfoDb_1.22.1                
[15] IRanges_2.20.2                      S4Vectors_0.24.3                   
[17] BiocGenerics_0.32.0                 JASPAR2018_1.1.1                   
[19] Signac_0.2.5                       

```

Thanks very much in advance!!

**Comment by timoast** [comment]
I think the easiest solution here is to convert the peaks to 1-based coordinates at the beginning, because there are going to be several places where it's converting from the string to granges and back again. If you run:

```r
peaks.1based <- GRangesToString(
  grange = StringToGRanges(
    regions = rownames(gata5wt13h),
    sep = c(":","-"),
    starts.in.df.are.0based = TRUE
  ),
  sep = c(":", "-")
)
```

This will convert everything to 1-based coordinates. If you then replace the peak names in the count matrix with the 1-based coordinates (`rownames(counts) <- peaks.1based`), it should avoid all these issues later.

**Comment by MengyiSong** [comment]
Hi Tim,

Thanks for your quick response! I had to replace the rownames for both counts and data matrix with the 1-based coordinates. It is working now! Thank you so much!

**Comment by zrcjessica** [comment]
Hi, I got a similar error running `AddMotifs()` - I have an integrated snATAC-seq dataset from rats, and I had to create a custom BSgenome package for it because we built our reference genome from the Ensembl genome annotation (['ftp://ftp.ensembl.org/pub/release-101/fasta/rattus_norvegicus/dna/Rattus_norvegicus.Rnor_6.0.dna.toplevel.fa.gz']('ftp://ftp.ensembl.org/pub/release-101/fasta/rattus_norvegicus/dna/Rattus_norvegicus.Rnor_6.0.dna.toplevel.fa.gz')). 

I made sure to use the same FASTA file used to create the cellranger reference (the one listed above) to create my BSgenome object. However, when I run `AddMotifs()`, I get the following error:

'''
Error in loadFUN(x, seqname, ranges): trying to load regions beyond the boundaries of non-circular sequence
  "7"
Traceback:

1. AddMotifs(object = dat, genome = BSgenome.Rnorvegicus.Ensembl.rn6, 
 .     pfm = pfm)
2. AddMotifs.Seurat(object = dat, genome = BSgenome.Rnorvegicus.Ensembl.rn6, 
 .     pfm = pfm)
3. AddMotifs(object = object[[assay]], genome = genome, pfm = pfm, 
 .     verbose = verbose)
4. AddMotifs.ChromatinAssay(object = object[[assay]], genome = genome, 
 .     pfm = pfm, verbose = verbose)
5. AddMotifs(object = granges(x = object), genome = genome, pfm = pfm, 
 .     verbose = verbose)
6. AddMotifs.default(object = granges(x = object), genome = genome, 
 .     pfm = pfm, verbose = verbose)
7. CreateMotifMatrix(features = object, pwm = pfm, genome = genome, 
 .     use.counts = FALSE)
8. motifmatchr::matchMotifs(pwms = pwm, subject = features, genome = genome, 
 .     out = "scores", ...)
9. motifmatchr::matchMotifs(pwms = pwm, subject = features, genome = genome, 
 .     out = "scores", ...)
10. matchMotifs(pwms_list, subject, ...)
11. matchMotifs(pwms_list, subject, ...)
12. .local(pwms, subject, ...)
13. getSeq(genome, subject)
14. getSeq(genome, subject)
15. .local(x, ...)
16. .extractFromBSgenomeSingleSequences(x, sseq_args$names, sseq_args$start, 
  .     sseq_args$end, sseq_args$width, sseq_args$strand)
17. lapply(seq_len(length(grl)), function(i) {
  .     gr <- grl[[i]]
  .     if (length(gr) == 0L) 
  .         return(DNAStringSet())
  .     seqlevel <- grl_seqlevels[i]
  .     is_circular <- isCircular(x)[[seqlevel]]
  .     idx <- match(seqlevel, x@user_seqnames)
  .     if (is.na(idx)) 
  .         stop("invalid sequence name: ", seqlevel)
  .     seqname <- names(x@user_seqnames)[[idx]]
  .     if (is.null(snplocs(x, seqname))) {
  .         subject <- try(get(seqname, envir = x@.seqs_cache, inherits = FALSE), 
  .             silent = TRUE)
  .         if (is(subject, "try-error")) {
  .             ans <- loadSubseqsFromStrandedSequence(x@single_sequences, 
  .                 seqname, ranges(gr), strand(gr), is_circular)
  .             return(ans)
  .         }
  .         .linkToCachedObject(subject) <- .newLinkToCachedObject(seqname, 
  .             x@.seqs_cache, x@.link_counts)
  .     }
  .     else {
  .         subject <- x[[seqlevel]]
  .     }
  .     masks(subject) <- NULL
  .     loadSubseqsFromStrandedSequence(subject, seqlevel, ranges(gr), 
  .         strand(gr), is_circular)
  . })
18. lapply(seq_len(length(grl)), function(i) {
  .     gr <- grl[[i]]
  .     if (length(gr) == 0L) 
  .         return(DNAStringSet())
  .     seqlevel <- grl_seqlevels[i]
  .     is_circular <- isCircular(x)[[seqlevel]]
  .     idx <- match(seqlevel, x@user_seqnames)
  .     if (is.na(idx)) 
  .         stop("invalid sequence name: ", seqlevel)
  .     seqname <- names(x@user_seqnames)[[idx]]
  .     if (is.null(snplocs(x, seqname))) {
  .         subject <- try(get(seqname, envir = x@.seqs_cache, inherits = FALSE), 
  .             silent = TRUE)
  .         if (is(subject, "try-error")) {
  .             ans <- loadSubseqsFromStrandedSequence(x@single_sequences, 
  .                 seqname, ranges(gr), strand(gr), is_circular)
  .             return(ans)
  .         }
  .         .linkToCachedObject(subject) <- .newLinkToCachedObject(seqname, 
  .             x@.seqs_cache, x@.link_counts)
  .     }
  .     else {
  .         subject <- x[[seqlevel]]
  .     }
  .     masks(subject) <- NULL
  .     loadSubseqsFromStrandedSequence(subject, seqlevel, ranges(gr), 
  .         strand(gr), is_circular)
  . })
19. FUN(X[[i]], ...)
20. loadSubseqsFromStrandedSequence(x@single_sequences, seqname, 
  .     ranges(gr), strand(gr), is_circular)
21. loadFUN(x, seqname, ranges)
22. loadFUN(x, seqname, ranges)
23. stop(wmsg("trying to load regions beyond the boundaries ", "of non-circular sequence \"", 
  .     seqname, "\""))
'''

I did notice that I had 0-based regions on chromosome 7. Do you have any idea what might be wrong? Thanks.
