### ISSUE TITLE
batch effect correction + label transfering

### ISSUE THREAD

**Issue by rojinsafavi** [timoast/signac#141]
I have 2 baches of ATACseq data each batch has 5 fragments file.
example:

Batch 0           Batch1
T1                     T1
T2                     T2
T3                     T3
T4                     T4
T5                     T5

and I have one scRNAseq object.

I would like to do two things
1. Label transferring from scRNA to ATACseq
2. Batch effect correction between ATACseq (batch0 and batch1)

I was wondering what would be the appropriate steps? 
Do you suggest doing the label transferring for each batch separately and then apply harmony? Or do you suggest to do the harmony fist between the ATAC batches, and then do the label transferring?

Thank you!

**Comment by timoast** [comment]
This is what I would suggest:

1. Follow the [merge](https://satijalab.org/signac/articles/merging.html) vignette to merge all 10 scATAC-seq objects (creating and quantifying a unified set of peaks and merging the fragment files and objects)
2. Run the standard analysis workflow on the merged dataset and check if there are batch effects by looking at the UMAP with cells colored by batch.
3. If there are no batch effects, proceed with label transfer from the scRNA-seq dataset as shown in the [vignettes](https://satijalab.org/signac/articles/pbmc_vignette.html#create-a-gene-activity-matrix-1). If there _are_ batch effects, run the Seurat integration method to integrate the gene activity matrices. It's important that you correct the gene activity matrix here rather than the scATAC data. Then run label transfer using the integrated gene activity matrix.

**Comment by rojinsafavi** [comment]
Thank you very much

**Comment by rojinsafavi** [comment]
Here are my steps, I would very much appreciate if you let me know if I am doing something wrong.

1. I did follow the merge script to merge all 10 scATAC files (from 2 different batches). I ran the following modules afterward and I saw a batch effect:
# make sure to change to the assay containing common peaks

```
DefaultAssay(t) <- "peaks" 
t <- RunTFIDF(t)
t <- FindTopFeatures(t, min.cutoff = 20)
t <- RunSVD(
  t,
  reduction.key = 'LSI_',
  reduction.name = 'lsi', 
  irlba.work = 400
)
t <- RunUMAP(t, dims = 2:30, reduction = 'lsi')
```

2. Just to clarify this, now you suggest to do the Quality control on the merged dataset (the QC section from https://satijalab.org/signac/articles/pbmc_vignette.html) before doing batch effect correction?
3.  label transfering

**Comment by timoast** [comment]
This looks fine, I would just call the object something other that `t` so that you don't overwrite the transpose function `t()` in R. You can do the QC before or after merging, whichever is more convenient. I do it before merging because I like to reduce the number of cells as soon as possible to make downstream steps faster. I would definitely do QC before any batch correction/integration

**Comment by rojinsafavi** [comment]
Thanks Tim,
One more question 

I should have made this clear, but I already know the broad region of each of the ATAC files that I have.

scATAC
            Batch0 Batch1
**region1** T1 T1
**region2** T2 T2
**region3**  T3 T3
**region4**  T4 T4
**region5**  T5 T5

Since I know the broad region, do you think it might be better to batch correct each of the regions independently? Since I already know that all the cell from Region1 of batch0 of T1 file should map to Region1 of batch2 of T1 file

**Comment by timoast** [comment]
Broad region is the tissue region? If you only are expecting equivalent cell states within a region across the two batches then it makes sense to integrate each pair of region batches separately and then merge the integrated datasets.

You will still need to quantify the same regions in all datasets in order to do the final merge, and make sure to batch-correct the same set of peaks in all the different regions (setting the `features.to.integrate` parameter in `IntegrateData`)

**Comment by rojinsafavi** [comment]
Yes, the broad region is the tissue region.

In that case, just to make sure that I'm getting it right:
1. I should still make a unified set of peaks using all the datasets
2. Batch correction on each region independently
3. Merging all the batch corrected objects
4.label transfer

Does that sound reasonable to you?

**Comment by timoast** [comment]
Sure, sounds reasonable

**Comment by rojinsafavi** [comment]
thank you very much!
