### ISSUE TITLE
Motif binding regions

### ISSUE THREAD

**Issue by Aitor91** [timoast/signac#152]
Hi @timoast ,

I have a question about the motif analysis. After this analysis, we know that there is a motif that is enriched in a specific cluster. Therefore, somehow we know that certain promoter sequences have higher accessibility for this motif sequence, therefore there are more likely to bind certain TFs. Can we know in which promoter regions these motifs are located? Maybe it is a crazy thing, but in my opinion, that could help to know which genes can be affected by which motif. 

Aitor

**Comment by timoast** [comment]
Hi Aitor, this makes sense and I think it could be a good idea and potentially help narrow down to the genes that are being regulated by different TFs. There is not currently a function to do this in signac but the information about what peaks contain what motifs is stored in the peak x motif matrix in the motif object. What you could do is:

1. Find the positions of each promoter

```r
library(EnsDb.Hsapiens.v75)

gene.ranges <- genes(EnsDb.Hsapiens.v75)
gene.ranges <- gene.ranges[gene.ranges$gene_biotype == 'protein_coding', ]
gene.ranges <- keepStandardChromosomes(gene.ranges, pruning.mode = 'coarse')
seqlevelsStyle(gene.ranges) <- 'UCSC'
gene.promoters <- promoters(gene.ranges)
```

2. Find which promoters overlap a peak

```r
library(GenomicRanges)
library(S4Vectors)

peaks <- StringToGRanges(regions = rownames(atac_small), sep = c(":", "-"))
hits <- findOverlaps(query = peaks, subject = gene.promoters)
promoter.peaks <- queryHits(hits)
```

3. Find which promoter peaks contain the motif

```r
motif.use <- "MA0497.1" # as an example

# find which promoter peaks contain the motif
promoter.peaks.with.motif <- GetMotifData(object = pbmc_small)[promoter.peaks, motif.use]
```

The results (`promoter.peaks.with.motif`) will be a binary vector where it's 1 if the peak contains the motif and 0 otherwise. You can use the `ClosestFeature` function to find which gene goes with each promoter, or use the `distanceToNearest` function in GenomicRanges. You could also do this for multiple motifs at once just by setting `motif.use` as a vector, or get the information for all motifs by leaving it out.

**Comment by Aitor91** [comment]
Hi @timoast ,

Thank you for the suggestion and help. I am working with that right now, so I will let you know how it goes.

Again, thank you for your help.

Aitor

**Comment by JulianaSuch** [comment]
Hi @timoast,

I was able to get the binary vector but am a little confused on how to use this vector to find the genes. Would you please elaborate further?

Thank you so much!
