### ISSUE TITLE
How can I deal with custom genome?

### ISSUE THREAD

**Issue by bingy007** [timoast/signac#173]
Hi,

Thanks a lot for your help!
I got a problem when applying the Signac to my 10X scATACseq data. Could you help me?
The question is we have cells expressing GFP. so we want to identify GFP+ cells in the ATACseq. 
Our reference genome is human+mouse+GFP, so I curated the reference genome to include all these three. But when I run Signac I found I cannot go through the "# create granges object with TSS positions" process. My contigs are "GRCh37_chr1, ..., X,Y" + "mm9_chr1,...,X,Y" + "GRCh37_chrGFP". And they are all in my .gtf file. I can load my .gtf as a custom genome. 
`gtf <- rtracklayer::import('genes.gtf')`
But cannot run the following cmds: 
```
gene.coords <- gtf[gtf$type == 'gene']
seqlevelsStyle(gene.coords) <- 'UCSC' 
  Error in .replace_seqlevels_style(x_seqlevels, value) : 
    found no sequence renaming map compatible with seqname style "UCSC" for this object
gene.coords <- keepStandardChromosomes(gene.coords, pruning.mode = 'coarse')
```

Can you help me with this?

Thank you!
Ale

**Comment by Puriney** [comment]
This is expected. The UCSC seq level style has no 'CRCh37_chr1', 'mm9_chr1' (the standard UCSC style is like chr1, chr2), but you force to set the 'seqlevelStyle' as 'UCSC'. So don't run the step `seqlevelsStyle(gene.coords) <- 'UCSC'`.


The function `keepStandardChromosomes` is to remove contigs other than chr1/2/.../X/Y/M. The function cannot understand 'mm9_chr1'. Therefore, you need to manually select the seqnames. Because genome is defined by yourself, you should know all the details. Use the function `keepSeqlevels` to choose what you need. http://web.mit.edu/~r/current/arch/i386_linux26/lib/R/library/GenomeInfoDb/html/seqlevels-wrappers.html

**Comment by mailcolm9** [comment]
Hi,

Thank you for your reply! 
I followed your suggetion and it works. But when I run the following cmd:
```
> pbmc[['RNA']] <- CreateAssayObject(counts = gene.activities2)
Non-unique features (rownames) present in the input matrix, making uniqueError: Cannot add a different number of cells than already present
```
I got this error, Does it mean my gene.activities2 matrix has duplicate logs? 
Could you help me deal with it?

Best,
Ale

**Comment by mailcolm9** [comment]
> Hi,
> 
> Thank you for your reply!
> I followed your suggetion and it works. But when I run the following cmd:
> 
> ```
> > pbmc[['RNA']] <- CreateAssayObject(counts = gene.activities2)
> Non-unique features (rownames) present in the input matrix, making uniqueError: Cannot add a different number of cells than already present
> ```
> 
> I got this error, Does it mean my gene.activities2 matrix has duplicate logs?
> Could you help me deal with it?
> 
> Best,
> Ale

Hi,
I found it in other question. 
I ran this:
`pbmc[['RNA']] <- CreateAssayObject(counts = gene.activities2[, colnames(pbmc)])`

And it works!

Thanks!

Ale
