### ISSUE TITLE
Tss position 

### ISSUE THREAD

**Issue by widsquid** [timoast/signac#176]
Hello, awesome analysis tools thanks so much. I am just wondering if I am missing something or does this function return the TSS for + strand genes and the end of the gene body for - strand genes. Forgive me if I do not understand something correctly.

tss.ranges <- GRanges(
  seqnames = seqnames(gene.ranges),
  ranges = IRanges(start = start(gene.ranges), width = 2),
  strand = strand(gene.ranges)
)

Instead I used the following to get the start site from genes on both strands.

wstss.ranges <- GRanges(
  seqnames = seqnames(gene.ranges), 
  ranges = IRanges(start = ifelse(strand(gene.ranges) == "+", start(gene.ranges), end(gene.ranges)), width = 2), 
  strand = strand(gene.ranges)
)

Is this legitimate to obtain these positions or have I made a mistake and or will this create problems somehow? Thanks again.
W

**Comment by timoast** [comment]
You're right, this is an error in the documentation. The code shown in the vignette would get the end of the - strand genes rather than the start. I'll update this as soon as I can, your code will work (although you could add a condition for "*" strand genes too). An easier way is to use the `resize()` function from GenomicRanges, eg:

```r
GenomicRanges::resize(gene.ranges, width = 1)
```

**Comment by timoast** [comment]
Fixed now on the website

**Comment by widsquid** [comment]
Great thanks so much Tim! Your work is very much appreciated.
W
