### ISSUE TITLE
About IntegrateData() function

### ISSUE THREAD

**Issue by chent5** [timoast/signac#183]
Thanks a lot for developing this very useful package. I have a question about the IntegrateData() function.

In the analysis of scATAC data (), weight.reduction = sci[['lsi']] and preserve.order = TRUE as below:
https://satijalab.org/signac/articles/integration.html
integrated <- IntegrateData(
  anchorset = anchors,
  weight.reduction = sci[['lsi']],
  dims = 2:30,
  preserve.order = TRUE
)

However, in the analysis of scRNA data, the above two arguments are using default parameters: weight.reduction = NULL and preserve.order = F.
https://satijalab.org/seurat/v3.2/integration.html
pancreas.integrated <- IntegrateData(anchorset = pancreas.anchors, dims = 1:30)

Are there any specific reasons for changing these parameters when analyzing scATAC data? Does it make sense if I used the default settings in scATAC analysis?

Thanks a lot for your explanation in advance!

**Comment by timoast** [comment]
As described in the documentation, `weight.reduction` controls what dimension reduction is used for weighting anchors. If NULL (the default), PCA is run on the query and the PCA space is used for weighting anchors. This is not what we want for scATAC-seq data, instead you should use the LSI space, which is why you need to pass either `weight.reduction="lsi"` or the LSI dimreduc object itself.

The `preserve.order` argument (again, this is explained in the docs) controls whether objects are reordered based on a sample tree or they are integrated in the order that they are supplied in the list of objects given to `FindIntegrationAnchors`. In the case where you are integrating only 2 objects, they will be reordered so that the larger object is the reference unless `preserve.order=TRUE`.
