### ISSUE TITLE
How to integrated the scATAC sample with scRNA

### ISSUE THREAD

**Issue by millersan** [timoast/signac#299]
Hi Tim,
Thanks a lot for developing this very useful package. I feel confused with the integrated scATAC samples to integrate with scRNA samples. Here are my steps to integrate the scATAC and scRNA, before the scATAC samples integrated.

#######################################
I: Follow "**_scATAC-seq data integration_**", to integrated two samples into one. I get the result with 3 assays: "sciPeaks", "peaks" and "integrated"

II: Set the Defultassay(sample) to "sciPeaks" because when I use the Defultassay as "integrated", I can't make the active gene matrix.

III: Make the active gene matrix and create it to sample[["RNA"]] 

IV: Remaining steps follow "Integrating with scRNA-seq data" in "**_Analyzing PBMC scATAC-seq_**"
#######################################

Is there anything wrong with my steps?

And I feel confused with the slot "integrated"

```
class(integrated@assays$sciPeaks)
[1]` "ChromatinAssay"
attr(,"package")
[1] "Signac"

class(integrated@assays$integrated)
[1] "Assay"
attr(,"package")
[1] "Seurat"
```

How to uesd the integrated slot?

Thank you so much!

**Comment by timoast** [comment]
If your goal is to transfer cell type labels, there's no point running the scATAC-seq batch correction as this isn't altering the gene activity values.

I'd suggest that you:
1. Follow the merge vignette to create a merged scATAC-seq object with the same set of peaks quantified in all cells
2. Quantify gene activities using the `GeneActivity` function
3. Follow the workflow shown in other vignettes to transfer cell type labels from a scRNA-seq dataset.

The reason you can't call `GeneActivity` on the integrated assay is that the integrated assay is a standard Seurat assay, rather than a Signac ChromatinAssay, and so is not linked to any scATAC-seq information.

**Comment by millersan** [comment]
![image](https://user-images.githubusercontent.com/46741428/96753867-12ee5a00-1403-11eb-92d8-ec3286d71ada.png)
I try the merge vignette, but it seems like 2 sample have very strong batch correction. That's why I try to used integrated assay.
Can you help me ? Thank you so much!
