### ISSUE TITLE
Name conflict

### ISSUE THREAD

**Issue by vyasr** [timoast/signac#33]
Hi there, 
I wanted to let you know that we've got an unfortunate naming conflict with your new package over at [glotzerlab/signac](https://github.com/glotzerlab/signac). We just received [an issue](https://github.com/glotzerlab/signac/issues/237) from one of your users, and I imagine that this problem will crop up again. Do you have any plans to roll your package into your [Seurat](https://github.com/satijalab/seurat) package at any point? That might alleviate this difficulty in the long term.

**Comment by timoast** [comment]
Hi @vyasr, sorry about the conflict, I was not aware of your package. Signac will not be merged into Seurat, but since these two packages serve completely different purposes and are in different languages I don't see this as a major issue. Similarly google released a package called Seurat for VR (https://github.com/googlevr/seurat) and it hasn't caused any problems for us and our Seurat package

**Comment by vyasr** [comment]
No worries, just wanted to let you know! I agree that we're in pretty different spaces and probably won't conflict.
