### ISSUE TITLE
batch correction for >2 objects

### ISSUE THREAD

**Issue by achieng33** [timoast/signac#369]
I'm having trouble merging 4 objects that have batch corrections (I followed the merge vignette and one object doesn't merge correctly)
I've tried following the steps outlined on this thread: https://github.com/timoast/signac/issues/141 but the issue I'm having with the integration vignette is that I'm unable to find common peaks between 4 objects (the findOverlaps function doesn't know what to do with a list of objects)

In my merged object I noticed that 3 out of 4 objects merged with no problem, and I'm wondering if it's at all possible to merge the 3 objects then use the integration method on the merged object and the 4th remaining object. Thanks!

**Comment by strawberry789** [comment]
I also have batch effects in my three scATAC objects.

#141 suggests to change the default assay containing the `combined.peaks`, but which one would that be?  The only active assay seems to be `ATAC`, as outlined in the merging vignette.

**Comment by strawberry789** [comment]
I followed your instructions from #141 

"If there are no batch effects, proceed with label transfer from the scRNA-seq dataset as shown in the vignettes. If there are batch effects, run the Seurat integration method to integrate the gene activity matrices. It's important that you correct the gene activity matrix here rather than the scATAC data. Then run label transfer using the integrated gene activity matrix."

So I did the following after UMAP revealed batch effects:

# compute gene activities
gene.activities <- GeneActivity(combined)

# add the gene activity matrix to the Seurat object as a new assay
combined[['RNA']] <- CreateAssayObject(counts = gene.activities)
combined <- NormalizeData(
  object = combined,
  assay = 'RNA',
  normalization.method = 'LogNormalize',
  scale.factor = median(combined$nCount_RNA)
)

# find integration anchors
DefaultAssay(combined) <- "RNA" 
integration.anchors <- FindIntegrationAnchors(
  object.list = list(combined),
  anchor.features = rownames(combined),
  reduction = "rlsi",
  dims = 3:30
)

And I got this error in the integration anchors step:
Error in which(x = object.classes, useNames = TRUE): argument to 'which' is not logical

After this step is done, do I do the following:
# integrate LSI embeddings
integrated <- IntegrateEmbeddings(
  anchorset = integration.anchors,
  reductions = combined[["lsi"]],
  new.reduction.name = "integrated_lsi",
  dims.to.integrate = 1:30
)

# create a new UMAP using the integrated embeddings
integrated <- RunUMAP(integrated, reduction = "integrated_lsi", dims = 3:30)
p2 <- DimPlot(integrated, group.by = "dataset")

Thanks!

**Comment by Pb208** [comment]
Hi there,
what did you do about that one error that occurred during FindIntegrationAnchors?

Cheers

**Comment by chenc327** [comment]
> 

@strawberry789 maybe you got something wrong. run integrated in your way should make sure that active assay is **PEAK** rather than gene score, and you should run TF-IDF first.
