### ISSUE TITLE
10x Multiomic assay on organsim whose genome is not available in Ensb or UCSC

### ISSUE THREAD

**Issue by martychat** [timoast/signac#376]
We have generated some 10x multiome (scRNA+ATAC) dataset in an organism for which we have a draft genome and annotation for but it's not a BSgenome genome package or EnsDB annotation package available on BioConductor.

Following the FAQ, I tried to use my GTF file using the rtracklayer. It ran only when I changed "Scaffolds" to "chr" in order to make it UCSC compatible. I hope I don't run into problems later. 

My goal has been to follow the vignette for 10x Multiomic but now I am confused as to what I should alter in this section which reads the annotation file:

#get gene annotations for hg38
annotation <- GetGRangesFromEnsDb(ensdb = EnsDb.Hsapiens.v86)
seqlevelsStyle(annotation) <- "UCSC"
genome(annotation) <- "hg38"

So any help where I can read my annotation file into the pipeline will be much appreciated.

**Comment by timoast** [comment]
The gene annotations do not need to have chromosome names prefixed with "chr", they need to match the chromosome names in the genome that the data was mapped to. If you changed the chromosome names in the gene annotations so that they don't match the genome, this would cause errors downstream (and is probably the cause of your other issue #377).

To format your gene annotations correctly for use with Signac, I'd suggest extracting a set of gene annotations for another genome as shown in the vignettes, and looking at the format they're in. You'd then need to modify your custom gene annotations to be the same format. Basically, it should be a `GRanges` object with `gene_name`, `gene_biotype`, and `type` columns.
