### ISSUE TITLE
Tn5 integration enrichment at a specific motif

### ISSUE THREAD

**Issue by ymuto802** [timoast/signac#42]
Hi Tim, 
The enrichment of Tn5 integration events at a specific motif, like TSS enrichment visualization in the vignette, would be very visually effective to show the motif activity in each cell-type (like Nat Biotechnol. 2019 Aug;37(8):925-936, Fig.2F). I guess it can be done using or modifying TSSenrichment / TSSPlot function...How do you think we can do this? I would be grateful if you could add it to the function or vignette when you have time.
Thanks!
Yoshi

**Comment by timoast** [comment]
Hi Yoshi, you mean TF footprinting? I can add that, I have worked on it a little bit already but have been busy with some other priorities lately. It can be tricky to do with ATAC-seq data because you need to correct for the sequence bias of Tn5, but I can implement the method used in that paper (https://www.nature.com/articles/s41587-019-0206-z).

**Comment by ymuto802** [comment]
Thanks Tim - Yes I mean TF foot-printing. I got it !

**Comment by timoast** [comment]
This has now been added in Signac 1.0.0. See the vignette here: https://satijalab.org/signac/articles/footprint.html
