### ISSUE TITLE
ClosestFeature

### ISSUE THREAD

**Issue by Brawni** [timoast/signac#47]
Hello!
I have been having troubles using the function ClosestFeature. I input a set of peak regions found to be differentially activated in cell clusters but i get the following error:

> peaks
 [1] "chr9-25677250-25678875"    "chr2-219252833-2192552861"
 [3] "chr1-201538135-201540645"  "chr6-33570673-33571808"   
 [5] "chr2-96536348-965394011"   "chr3-194002751-194004173" 
 [7] "chr12-55846923-55849266"   "chr11-111734956-111736614"
 [9] "chr9-130845807-130848326"  "chr10-3172019-31735621"   
[11] "chr7-108001168-108004822" 
> ClosestFeature (region= peaks, annotation = genes(TxDb.Hsapiens.UCSC.hg38.knownGene), sep=c('-','-'))
Error in .Call2("solve_user_SEW0", start, end, width, PACKAGE = "IRanges") : 
  In range 2: at least two out of 'start', 'end', and 'width', must
  be supplied.
In addition: Warning message:
In .normargSEW0(end, "end") : NAs introduced by coercion to integer range

If i remove peaks region two then it works fine, but i still would like what is happening there.

> peaks <- peaks[-2]
> ClosestFeature (region= peaks, annotation = genes(TxDb.Hsapiens.UCSC.hg38.knownGene), sep=c('-','            gene_id                    region distance
286319       286319    chr9-25676389-25678440        0
107985246 107985246  chr1-201507241-201534784     3350
449520       449520    chr6-33540046-33589026        0
9936           9936  chr2-159768628-159798255        0
647323       647323  chr3-193957372-194003760        0
4327           4327   chr12-55835433-55842966     3956
5519           5519 chr11-111726908-111766389        0
25               25  chr9-130713016-130887675        0
9712           9712   chr10-11453946-11611754        0
3912           3912  chr7-107923799-108003187        0

However, why the peak regions are all different from the ones i input?

Thanks a lot!

**Comment by timoast** [comment]
The first error is because you have a range that is nearly 2 billion bases long (2192552861 - 219252833 = 1973300028). I guess you have an error somewhere in the way you're generating these regions. If you remove the last digit in the end coordinate it's 2453 bp which seems more reasonable.

The region column in the output of `ClosestRegion` refers to the coordinate of the closest region in the annotation. The order of the rows will correspond to the order of the input regions, eg the second row gives the closest feature to the second genomic range in the input. I see how this is confusing and will update the format of the output to include both the coordinate of the query and the coordinate of the closest region.

**Comment by Brawni** [comment]
Hi Tim,

Removing those regions indeed solved the issue, thanks! However those regions might also be real? I guess i can look into them in other ways.
Thanks too for updating the ClosestRegion output that would help a lot.

Cheers!

**Comment by timoast** [comment]
Human chr2 isn’t 2 B bases long so it’s definitely an error somewhere, not a real peak
