### ISSUE TITLE
FRiP greater than 1 in multiome dataset

### ISSUE THREAD

**Issue by gouinK** [timoast/signac#489]
Greetings, I am working on a 10x multiome dataset and had a question about the FRiP calculation. I am using the CountFragments function prior to running the FRiP calculation, and I noticed that the resulting dataframe from CountFragments has a column labelled "frequency_counts" and a column labelled "reads_counts." When I use the "frequency_counts" column my resulting FRiP values are sometimes greater than 1, which would not theoretically be possible. When I use the "read_counts" column the results are more in line with what I would expect, as well as being in line with what the Cellranger web_summary.html file shows. I also noticed that I had to manually set the rownames of the CountFragments dataframe to the cell barcodes. 

I was following the bottom of this vignette [https://satijalab.org/signac/articles/pbmc_vignette.html#find-differentially-accessible-peaks-between-clusters-1]

Does all of this seem correct?

Thanks for your help and great package!

**Comment by timoast** [comment]
I think it depends what you're using as the numerator in you FRiP calculation. The "frequency_count" is the total fragment for the cell, and the "reads_counts" is the total reads for the cell (admittedly we could name these better). Since each fragment can be sequenced multiple times, it's expected that frequency_counts <= reads_counts. If you use the read count in your FRiP calculation and fragment count as the denominator, you could get a value >1. If you use fragment count for both, then you shouldn't have any FRiP > 1.
