### ISSUE TITLE
Error when calling  CreateChromatinAssay

### ISSUE THREAD

**Issue by MzwaneleN** [timoast/signac#690]
Hi, I am trying to create a  ChromatinAssay using the following code:

```r
snATAC_assay <- CreateChromatinAssay(counts = counts,
  sep = c(":", "-"), genome = "hg19",
  fragments = "C:/path/to/Desktop/GSM4887677_screen1_snATAC.tsv",
  min.cells = 1)

Error: Error in .get_data_frame_col_as_numeric(df, granges_cols[["start"]]) : 
  some values in the "start" column cannot be turned into numeric values
In addition: Warning message:
Expected 3 pieces. Missing pieces filled with `NA` in 28755 rows [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, ...]. 
```

Also I struggle to call: head(GSM4887677_screen1_snATAC.tsv)

```
Error: Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'head': object 'GSM4887677_screen1_snATAC.tsv' not found
```

Makes me think there are characters in the chromosome coordinates?

**Comment by timoast** [comment]
What delimiters are used in your count matrix to separate chromosome, start, end positions? Can you show the output of `head(rownames(counts))`?

The second error is likely because your fragment file is not the correct format. Your file ends with `.tsv`, which suggests it is not bgzip-compressed and indexed.

**Comment by timoast** [comment]
Closing this since I haven't heard back, please reopen if you're still having issues and can provide the requested information

**Comment by aj088** [comment]
Hi I got similar errors:
Expected 3 pieces. Missing pieces filled with `NA` in 108377 rows [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, ...].Error in .get_data_frame_col_as_numeric(df, granges_cols[["end"]]) : 
  some values in the "end" column cannot be turned into numeric values

any ideas of how to resolve this? Thanks

**Comment by markphillippebworth** [comment]
I hit this issue as well, and it's because the tile names are not properly parseing. It's resolving by setting the separator appropriately. 
In my case, I was using the format chrX:100-200, so I just need to set sep = c(":", "-")

Example:
chromatinassay <- Signac::CreateChromatinAssay(counts = fragTmp[unique(unlist(allTiles)),],   
                                                                   sep = c(":", "-"), 
                                                                    genome = "hg38")
