### ISSUE TITLE
EnsDb.Hsapiens.v86 vs hg38

### ISSUE THREAD

**Issue by hjack123** [timoast/signac#79]
Hi Tim,

Im puzzled by the feature plots ie gene activity matrix results.  Im wondering if EnsDb.Hsapiens.v86 is equivalent with hg38. my alignment was done on hg38 by 10x pipeline. would it be correct to use EnsDb.Hsapiens.v86? thanks so much.

**Comment by timoast** [comment]
I believe EnsDb.Hsapiens.v86 is for hg38 and EnsDb.Hsapiens.v75 is for hg19

Looking at the raw gene activities (accessibility in gene body and promoter) is often not that informative because it can be very sparse/noisy, we mainly recommend computing the gene activity for the purpose of integrating with scRNA-seq data where signal is pooled over many genes to perform the integration.

**Comment by Connorr0** [comment]
Also for future reference this [table](https://uswest.ensembl.org/info/website/archives/assembly.html) should tell you which EnsDb version corresponds to which genome. You can sometimes find the specific patch version for your reference by going into your reference and doing the following `cat refdata-cellranger-atac-mm10-1.2.0/metadata.json`, the patch number is sometimes in the ftp path (for mm10 I had to email ncbi to get the patch number form the path before).

**Comment by Connorr0** [comment]
It looks like the US west mirror has been retired. If but a similar link for US east should work:
https://useast.ensembl.org/info/website/archives/assembly.html
