### ISSUE TITLE
Integration of scATAC-seq data-general questions

### ISSUE THREAD

**Issue by annamath** [timoast/signac#86]
Hello, 

I have some questions regarding scATAC-seq data integration using Seurat/Signac.

Specifically, I am concerned for the case of merging 2 (or more) scATAC-seq datasets produced with 10x Genomics Technology (v3). These datasets come from the same human primary cell types in different age groups. Most of my downstream analysis is based on this vignette: 
https://satijalab.org/signac/articles/integration.html

First of all, I was wondering if the integration and 'harmonisation' of these 2 datasets will end up removing not only the 'batch' effects but possibly also biology-related differences. From what I understand from "Comprehensive integration of Single-Cell Data" (2019, Cell), looks like that the 'anchor' identification approach can result in biases regarding only shared cell-types. 
Q1 - Is this accurate? Would you suggest a different approach in order to account for merging 2 datasets that are not entirely coming from the same system and identification of dataset-unique cells? 

Also, while reading your answers in the issue here: https://github.com/timoast/signac/issues/35 it is mentioned:
"I think this is a description of one way dataset merging can work for scATAC-seq data. This is similar to what MergeWithRegions does, only that there is no centering of peaks in that function (for convenience we keep the peak coordinates of one of the input datasets)."
Q2 - Have you seen this approach resulting in peak-bias towards one of the two datasets? 

In the integration vignette (mentioned above) at some point it is mentioned:  
"In order to have common features across the datasets we want to integrate, we can count reads in the sci-ATAC-seq peaks in the 10x Genomics dataset and create a new assay with these counts. For efficiency, we will downsample the sci-ATAC-seq peaks used. We have found integration results to be quite robust to the number and set of peaks used."
Q3 - Does the size/number of peaks selected for integrating data affects the result? Here you mean that for integrating the data, you use let's say 10.000 peaks and this is consistent in different numbers as well? E.g. in 20.000 peaks etc.? 

Q4 - Finally, it is not so clear to me which approach is the 'best' to follow. After the points highlighted above I would say: 
- Identify the union of peaks between both datasets ~ a consensus peak set using GRanges (going back to Q3, do I keep all the peaks or should I select a number of peaks? )
- Quantify for new 'consensus peak set' in both datasets 
- Find anchors (FindIntegrationAnchors()) 
- Integrate data (IntegrateData())
... downstream steps 

Thank you in advance! 
Looking forward to hearing back from you. 

Anna

**Comment by timoast** [comment]
Hi Anna,

>  I was wondering if the integration and 'harmonisation' of these 2 datasets will end up removing not only the 'batch' effects but possibly also biology-related differences.

In your case it sounds like batch and age group are confounded (each age group is a different batch), so it will be hard to know what are the differences due to batch and what are due to age group. However, if you have multiple replicates for each age group you will be able to look for things that are consistent across replicates. Note that we recommend integration as a method to identify common cell states across the different experiments, but you should always use the original gene expression measurements when performing differential expression. You can do a differential expression test that takes latent variables (eg, batch) into account using `FindMarkers` arguments `test.use="LR", latent.vars="batch"`.

> From what I understand from "Comprehensive integration of Single-Cell Data" (2019, Cell), looks like that the 'anchor' identification approach can result in biases regarding only shared cell-types.

The integration methods we developed are quite robust to unshared cell types across the different datasets. See for example figure 2 or figure 3b in the [paper](https://www.sciencedirect.com/science/article/pii/S0092867419305598?via%3Dihub)

> Also, while reading your answers in the issue here: #35 it is mentioned:
"I think this is a description of one way dataset merging can work for scATAC-seq data. This is similar to what MergeWithRegions does, only that there is no centering of peaks in that function (for convenience we keep the peak coordinates of one of the input datasets)." 
> Q2 - Have you seen this approach resulting in peak-bias towards one of the two datasets?

No, in this case we're only using the peak **names** from one dataset so that the features have consistent names across both datasets, but the peak coordinates originate from both datasets.

> Q3 - Does the size/number of peaks selected for integrating data affects the result? Here you mean that for integrating the data, you use let's say 10.000 peaks and this is consistent in different numbers as well? E.g. in 20.000 peaks etc.?

In my experience the exact number or set of peaks used does not seem to have a major effect on the integration results, as long as more than ~10,000 peaks are used. You can try with different sets of peaks on your own data and see how the results differ.

> Q4 - Finally, it is not so clear to me which approach is the 'best' to follow. After the points highlighted above I would say:

Yes, this is a reasonable workflow. I think re-quantifying consensus peaks across datasets is a better approach than just using intersecting peaks, but can take some extra time.
