### ISSUE TITLE
metadata missing

### ISSUE THREAD

**Issue by Leonrunning** [timoast/signac#924]
Hi Signac,

The file of "per_barcode_matrices.csv" is missing from the output of cellranger-arc aggr on multiple samples analyzed by cellranger-arc. Do you have any idea for how to generate a metadata in this case?  I know it should be the issue with cellranger but just check to see if there are any other methods to generate this part of information.

thanks in advance

**Comment by Leonrunning** [comment]
Hi @timoast,

I have to reopen this issue as the "peak_region_fragments" is missing in my object as its metadata is not produced from the outputs of cellranger-arc aggr.  I have avoided to use this parameter for quality control, but it is necessary for the "FindMarkers" function.

Do you have any suggestions to add this metadata through Signac? Or shall I have to process the fragments using other packages before loading onto Signac? Any suggestions would be highly appreciated!

Thanks
Leon

**Comment by tilofreiwald** [comment]
Currently, according to the 10x support, `cellranger-arc aggr` does not support the generation of the metadata you mention ("`singlecell.csv`" in the `cellranger-atac aggr` pipeline). However, I think you could take the individual samples' `per_barcode_metrics.csv`'s and rename their barcode suffixes and discard the atac_peak columns (because `aggr` redoes peak calling) and load it into your Seurat object.
