### ISSUE TITLE
[W::hts_idx_load2] The index file is older than the data file

### ISSUE THREAD

**Issue by fangfang0906** [timoast/signac#933]
Hi, Thanks for developling signac. I'm processing a 10x multiome dataset. When running "NucleosomeSignal()" and "CoveragePlot()", I got this warning "[W::hts_idx_load2] The index file is older than the data file". What can be possible reasons? Will it affect the results? Thanks!

**Comment by timoast** [comment]
It means that the index file is newer on the filesystem than the fragment file itself, which wouldn't normally be expected since you create the index from the fragment file. However, if you download or move files the index could appear newer since it can be written before the larger fragment file. This warning can basically be ignored, it comes from the Rsamtools package that we use internally. We could consider silencing these warnings in the Signac code in future, they can be annoying
