### ISSUE TITLE
gene activity matrix

### ISSUE THREAD

**Issue by ahmedabbas81** [timoast/signac#95]
Hi,

When calculating the gene activity matrix, are you internally binarizing the number of reads within each peak in a given cell? Or you count all the reads as I understood in the example here: https://satijalab.org/signac/articles/pbmc_vignette.html?

Thank you

**Comment by timoast** [comment]
The function [`FeatureMatrix`](https://satijalab.org/signac/reference/FeatureMatrix.html) (that we use to create a gene activity matrix) will sum the number of fragments overlapping the each genomic region in each cell, no binarization is performed. Note that fragments are summed, rather than reads, so that PCR duplicates are collapsed.

**Comment by ahmedabbas81** [comment]
Thank you,

And for the function CreateGeneActivityMatrix(), does it internally binarize the peaks to either 0 or 1?

Or it just sums the counts in the peak entries without binarization?

Or should I ask in Seurat github?

Thank you

**Comment by timoast** [comment]
The `CreateGeneActivityMatrix` function in Seurat doesn't perform any binarization either, it just sums peaks intersecting the gene body and promoter region.

**Comment by ahmedabbas81** [comment]
Yes, I also understood that from the tutorials. and I noticed that in your example in https://satijalab.org/signac/articles/pbmc_vignette.html , all the processing was done without binarization including dimensionality reduction and everything. So, is this considered correct?

And if the number of reads within a peak is greater than number of reads in another peak, this can be interpreted that it may be a peak of bigger size for example or more open?

Thank you

**Comment by timoast** [comment]
Yes, PCR duplicates are collapsed in the fragments file so any counts >1 are likely not due to PCR duplication. We don't typically recommend binarizing the data, however we do have a function to do this if you would like to test the effect of binarization on your dataset: https://satijalab.org/signac/reference/BinarizeCounts.html
